### ISSUE TITLE
Demo closed

### ISSUE THREAD

**Issue by ZaK3939** [Nysm-Inc/philand-demo#122]
- [x] stop old landing page
- [x] close phi demo 
- [x] destory old coupon api 
- [x] link to LP
