### ISSUE TITLE
Land Edit (for UX review)

### ISSUE THREAD

**Issue by open3x** [Nysm-Inc/philand-demo#124]
### issues
- [ ] move object UX (like the webb)
- [ ] click trash
- [ ] switch current ENS
- [ ] connect to contract
