### ISSUE TITLE
L1 map Contract implement

### ISSUE THREAD

**Issue by ZaK3939** [Nysm-Inc/philand-demo#36]
Scope
- create unit test
- integration test
- object claim and write

Sprint2
- [x] Link method impl
- [x] create unit test (for fail case)
- [x] Event and error 
- [x] contract upgrade
