### ISSUE TITLE
Land Edition Frontend (For design review)

### ISSUE THREAD

**Issue by consome** [Nysm-Inc/philand-demo#7]
Scope
- Why
To check UI Behavior

- Want 
- [x] Switch view/edit mode
- [x] Tile System
- [ ] Zoom in / Zoom out
- [ ] Move center camera
- [x] Place object /can be moved.
- [x] Open modal (shop, collection...)
- [x] Open action menu (when click an object)

-------
- Clarify 
  - tasks
  - minimum demo 

- Currently No need
  - contract interact
  - tx status
  - manage current ENS
  - css styling

**Comment by open3x** [comment]
![Screen Shot 2022-05-12 at 20.34.31.png](https://images.zenhubusercontent.com/62386e762280cd5d8cc37161/512499a3-5d97-4004-9f4b-cb5c80b7df59)
